services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

  evlampiy_notes_tgbot:
    restart: always
    depends_on:
      - mongodb
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - WIT_RU_TOKEN=${WIT_RU_TOKEN}
      - WIT_EN_TOKEN=${WIT_EN_TOKEN}
      - WIT_ES_TOKEN=${WIT_ES_TOKEN}
      - WIT_DE_TOKEN=${WIT_DE_TOKEN}
      - MONGO_URI=${MONGO_URI}
      - GPT_TOKEN=${GPT_TOKEN}
