name: 'Checkout'
description: 'Checkout a repository'
inputs:
  repository:
    description: 'Repository to checkout'
    required: false
  ref:
    description: 'The branch, tag or SHA to checkout'
    required: false
runs:
  using: 'composite'
  steps:
    - run: |
        git clone https://github.com/${{ inputs.repository }}.git .
        git checkout ${{ inputs.ref }}
      shell: bash
